### ISSUE TITLE
The username variable keeps incremating when you refresh the HTML page

### ISSUE THREAD

**Issue by AvogatoWizardWhisker** [waitwhatActo/HomeworkSMP#3]
When you view the HTML file from browser, and keep refreshing it (basically spamming f5 key), the `usernames` variable of `@avogato_the_ailurophile` and `@williamhorning` keeps incrementing.

![image](https://github.com/user-attachments/assets/da1425a4-0f73-43f1-b7bc-ca2e51ab63f7)

# Steps to reproduce
1. View the `index.html` file from browser.
2. Keep refreshing the page and view the HTML code in your IDE.
3. You'll notice some usernames keeps incrementing.

**Comment by waitwhatActo** [comment]
The number corresponds to the image number and was added for debugging. Can be removed.
